name: CI

on:
  push:
    branches:
      - trunk
      - lab-1
  pull_request:
    branches:
      - trunk
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Debug

      - name: Run tests
        working-directory: build\test\Debug
        run: |
          .\WinShell-test.exe

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: WinShell.exe
          path: |
            build\source\Debug

  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Optionally generate compile_commands.json

      - uses: ZedThree/clang-tidy-review@v0.20
        id: review

      # Uploads an artefact containing clang_fixes.json
      - uses: ZedThree/clang-tidy-review/upload@v0.20
        id: upload-review

      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1