name: CI

on:
  push:
    branches:
      - trunk
      - lab-1
  pull_request:
    branches:
      - trunk
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Debug

      - name: Run tests
        working-directory: build\test\Debug
        run: |
          .\WinShell-test.exe

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: WinShell.exe
          path: |
            build\source\Debug

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}

