name: CMake

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  build:
    strategy:
      matrix:
        cmake_build_type: [Asan, Release]

    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' 
          choco install visualstudio2019community --params "/NoWeb"
          choco install visualstudio2019buildtools --params "/NoWeb"
          choco install llvm

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
          key: ${{ github.job }}-${{ matrix.cmake_build_type }}

      - name: Prepare
        run: |
          set CC=clang
          set CXX=clang++
          bash ci/prepare.bash ${{ matrix.cmake_build_type }}

      - name: Precommit
        if: matrix.cmake_build_type == 'Release'
        run: bash ci/precommit.bash check --style

      - name: Precommit (no style checks)
        if: matrix.cmake_build_type == 'Asan'
        run: bash ci/precommit.bash check --no-style
